### ISSUE TITLE
export socialcalc formulas to excel

### ISSUE THREAD

**Issue by eddyparkinson** [SheetJS/js-harb#10]
Ethercalc fails to export formulas to excel.

2 issues are involved
1) This fix is required https://github.com/mcsf/js-xlsx/commit/d439645
2) SheetJS/js-harb does not support exporting of socialcalc formulas
 the formula would need to be copied into the object.

**Fix**
I am happy to fix this - but with https://github.com/SheetJS  pull requests are being ignored - Abandoned?

**Comment by SheetJSDev** [comment]
We've merged this module into [js-xlsx](https://github.com/SheetJS/js-xlsx), and it is addressed there by [emitting `'vtf'` records on cells with formula](https://github.com/SheetJS/js-xlsx/blob/master/bits/40_harb.js#L648) and [grabbing the last field of a cell record of type `'vtf'`](https://github.com/SheetJS/js-xlsx/blob/master/bits/40_harb.js#L598)
