### ISSUE TITLE
Phone numbers lose leading 0

### ISSUE THREAD

**Issue by SystemParadox** [SheetJS/js-harb#3]
Hi,

When parsing a csv, a field containing a phonenumber such as '01234567890' loses its leading '0' to become '1234567890'.

Could we ensure that js-harb always produces strings, without any other conversions?

Thanks.

**Comment by dominickp** [comment]
I've also encountered this. Is there a workaround anyone has come up with?

**Comment by SheetJSDev** [comment]
We've merged this module into [js-xlsx](https://github.com/SheetJS/js-xlsx), and it is addressed there by emitting a string if the first character of a possible number is 0
