### ISSUE TITLE
Global leak

### ISSUE THREAD

**Issue by simon-p-r** [SheetJS/js-harb#6]
Hi

I am using j in a module I am writing and when testing it complains about global leak which is coming from 20_deps.js in the bits directory.  Is there no other way of exposing variables?  

Thanks

**Comment by reviewher** [comment]
@simon-p-r this is intentional.  Globals are the main way to support browser script tags to pull in optional dependencies

**Comment by simon-p-r** [comment]
You could package up interface more cleanly to prevents but his, but it is what it is! Thanks for the response
